name: Syndicate to mastodon
on:
  push:
    branches:
      - main
    paths-ignore:
      - uploads/**

jobs:
  Feed2Mastodon:
    outputs:
      tootUrl: ${{ steps.feed.outputs.tootUrl }}

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Checkout the repository to restore previous cache
      - name: Checkout
        uses: actions/checkout@v3

      - name: Wait for deply
        run: sleep 60s
        shell: bash

      # Look for new toots to create from items in the JSON feed
      - name: Feed to Mastodon
        id: feed 
        uses: nhoizey/github-action-feed-to-mastodon@v2
        with:
          feedUrl: "https://mycabinetofcuriosities.com/feed/syndicate-mastodon-json.json"
          mastodonInstance: "https://mastodon.social"
          mastodonToken: ${{ secrets.MASTODON_TOKEN }}
          testMode: false
          ignoreFirstRun: false
          globalDelayToots: 0

      # Make sure files are up to date if other commits have been pushed in the mean time
      - name: Pull any changes from Git
        run: git pull

      # Push changes in the cache files to the repository
      # See https://github.com/stefanzweifel/git-auto-commit-action#readme
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5

  UpdateSyndication:
    runs-on: ubuntu-latest
    needs: Feed2Mastodon
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add syndication link
        uses: AdamWier/micropub-action@18bd3e5d34d1619c5163e3ebfdc4832fbcfabc3b
        if: ${{ needs.Feed2Mastodon.outputs.tootUrl }}
        with:
          endpoint: "https://example.com/micropub"
          token: ${{ secrets.MICROPUB_TOKEN }}
          feedUrl: "https://mycabinetofcuriosities.com/feed/syndicate-mastodon-json.json"